// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sxofivqcxfpwxatixqwy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN4b2ZpdnFjeGZwd3hhdGl4cXd5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxMzQwMTYsImV4cCI6MjA2OTcxMDAxNn0.577yca9sYuoLS0rtUjJ0kcYZrtKXZvbsFAS5ylQBv4Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});